### ISSUE TITLE
Slashing Burst error

### ISSUE THREAD

**Issue by OuYangPlane** [Suprcode/Crystal#810]
The animation playback method is wrong. The official correct skill animation should be an action of raising the knife and leaning back. This action will have an obvious pause, but it will not be too long. After a certain distance, do another attack action.

https://www.youtube.com/watch?v=3ejV0UYZDIA&t=14s

**Comment by Lilcooldoode** [comment]
https://github.com/Suprcode/Crystal/commit/15d1ccddf38f73c81792a7824dbe95e74d9356e5
