### ISSUE TITLE
A long-standing problem

### ISSUE THREAD

**Issue by angelk727** [Suprcode/Crystal#825]
During team mode, Player A has a hero while Player B does not. Under normal circumstances when Player A’s hero attacks, Player B’s client operates normally. However, when Player A’s hero uses a skill, Player B’s client experiences a lag in the video.

**Comment by angelk727** [comment]
In team mode, if you summon a monster that can use magic, this type of problem may occasionally occur. But the Taoist's "Shinsu" and "HolyDeva" are not a problem.

**Comment by JevLOMCN** [comment]
This was raised before, I believe some hero spells were the cause of the lag.

**Comment by meacher0** [comment]
I think this might have been [](https://www.lomcn.net/forum/threads/client-freeze-hero-health-whilst-in-party.112351/) which is resolved in #951 ?
