### ISSUE TITLE
On the improvement of server and client

### ISSUE THREAD

**Issue by sddzrxh** [Suprcode/Crystal#919]
end...

**Comment by sddzrxh** [comment]
Auction function BUG, auction 1000 gold coins, you enter 10000, then return 10000 gold coins to the player.

**Comment by JevLOMCN** [comment]
Upload this: https://www.123pan.com/s/eYRDjv-idke.html extraction code: DDDD onto a different site please. Something like Google Drive/Mega/dropbox or [Filebin](https://filebin.net/)

**Comment by sddzrxh** [comment]
I am unable to log in to other cloud drives because the speed is too slow
![QQ图片20240228053856](https://github.com/Suprcode/mir2/assets/42303818/d22cc3cc-332f-4557-9710-95be377aee0a)
![QQ图片20240228053909](https://github.com/Suprcode/mir2/assets/42303818/951183a9-b6ba-4727-a6c0-409c01d2638b)
![QQ图片20240228054002](https://github.com/Suprcode/mir2/assets/42303818/3e162726-17e1-432a-b991-8d2592d32867)
![QQ图片20240228054020](https://github.com/Suprcode/mir2/assets/42303818/d9a62767-6e06-4663-aedf-2e60352a719c)
![QQ图片20240228054035](https://github.com/Suprcode/mir2/assets/42303818/2ec58aa6-5610-4773-a658-2e321bb3d7a9)
![QQ图片20240228054105](https://github.com/Suprcode/mir2/assets/42303818/e2477d4e-7e0a-4c4c-aaef-fde20d1d2076)
![QQ图片20240228054115](https://github.com/Suprcode/mir2/assets/42303818/cbd3f460-ef91-4c46-b9e2-0be8b695620e)
![QQ图片20240228054137](https://github.com/Suprcode/mir2/assets/42303818/3568a2f5-a9e3-44ad-8bc1-1107fcfa9856)

**Comment by JevLOMCN** [comment]
There is no way we can download anything using 123pan
