### ISSUE TITLE
Resurrection skill cannot be cast

### ISSUE THREAD

**Issue by xc1258** [Suprcode/Crystal#922]
I followed the author's advice to change the attack mode and equipped the resurrection charm. However, the skill is still ineffective. I hope it can be fixed.

**Comment by xc1258** [comment]
The vital skill of the Taoist's resurrection cannot be used, ?????.

**Comment by MousaEqilan** [comment]
if you mean Reincarnation you need wear AmuletOfRevival shape 3 and allow target dead option
