### ISSUE TITLE
Major - NPC Sale list

### ISSUE THREAD

**Issue by daneo1989** [Suprcode/Crystal#968]
Each NPC sale list will update with previous NPC sale list opened. 

![image](https://github.com/Suprcode/Crystal/assets/6216097/90eaeb0c-1a2d-4b5e-9d6a-3485197ff566)
****

![image](https://github.com/Suprcode/Crystal/assets/6216097/9c7f97ea-d99d-4573-a732-c819efaf5d82)

**Comment by meacher0** [comment]
I cant seem to re-create this. 
Clicking a new NPC closes the current sale window for me, then when new one opens, has the right stuff.

**Comment by meacher0** [comment]
[NPC Sale list bug](https://youtu.be/Z-E23pYk-_c)
Managed re-create it, took a 3rd NPC tho =/ 
How very odd...

**Comment by JevLOMCN** [comment]
Might be worth noting this is also found in Mir 1, I noticed it a few weeks back when testing some NPC scripts. I thought it was a script issue but after checking both NPC scripts I couldn't see any issue.

**Comment by sddzrxh** [comment]
The "credit" consignment of consignment NPC is also not open, and the source code seems to hide this function.

**Comment by damianday** [comment]
I'll have a look at this one tomorrow, if nobody beats me to it, either a client cache error or server error somewhere

**Comment by ezrgood** [comment]
Any update on this issue? Getting it on all my npcs
