### ISSUE TITLE
Command BUG

### ISSUE THREAD

**Issue by Jinspang** [Suprcode/Crystal#992]
If you are a GM, create a guild.

@CREATEGUILD  SSSSS    UKSNNNN

At this time, if you adjust the LEVEL with level, the guild will be dissolved immediately (level 1-26 is normal, level 26 or above is wrong).
If it is LEVEL to guild members, then the members will be kicked out of the guild.

-------------------------------------------
Add Skill Server Crash (Player Name)
If you are GM, add skills to yourself (other players have not tested)
If the player's name is 111 or 222 or asd letters

@GiveSkill  3 3      Server crash
@GiveSkill  25 3      Server crash

-------------------------------------------
The inventory of goods in the game mall is set to 5, and it can still be purchased indefinitely in the game.

**Comment by Jinspang** [comment]
![image](https://github.com/user-attachments/assets/91ddbb51-ac67-4651-a9ce-7240005f3033)
These three helmets should be displayed outside.

**Comment by damianday** [comment]
I cannot reproduce the CreteGuild bug
